apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecom-classifier
  name: ecom-classifier
spec:
  ports:
    - name: classify
      port: 8080
      targetPort: 8080
  selector:
    app: ecom-classifier
  type: LoadBalancer
